# Generated by Django 5.0.6 on 2026-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10),
        ),
    ]
